Exercise 6.1

a)

Junction $V_1$:
$$4V_1 -V_2-V_3-V_4=V_+.$$
Junction $V_2$:
$$V_2 - V_1 + V_2-V_4 + V_2=0,$$
$$3V_2 - V_1 - V_4 = 0.$$
Junction $V_3$:
$$V_3 - V_+ +V_3-V_1 + V_3-V_4=0,$$
$$3V_3 -V_1-V_4=V_+.$$
Junction $V_4$:
$$V_4-V_3 + V_4-V_1 + V_4-V_2 + V_4=0,$$
$$4V_4 - V_1 - V_2 - V_3=0.$$

In [8]:
import numpy as np
#b)
A = np.array([[4, -1, -1, -1],
              [-1, 3, -1, 0],
              [-1, 0, 3, -4],
              [-1, -1, -1, 4]
], float)

v = np.array([5, 0, 5, 0], float)
N = len(v)

#Gaussian elimination
for m in range(N):
    div = A[m,m]
    A[m, :] /= div
    v[m] /= div
    print(A)
    for i in range(m+1, N):
        mult = A[i, m]
        A[i, :] -= mult*A[m, :]
        v[i] -= mult*v[m]
        
#Backsubstitution
x = np.empty(N, float)
for m in range(N-1, -1, -1):
    x[m] = v[m]
    for i in range(m+1, N):
        x[m] -= A[m, i]*x[i] 
    
print(x)

[[ 1.   -0.25 -0.25 -0.25]
 [-1.    3.   -1.    0.  ]
 [-1.    0.    3.   -4.  ]
 [-1.   -1.   -1.    4.  ]]
[[ 1.         -0.25       -0.25       -0.25      ]
 [ 0.          1.         -0.45454545 -0.09090909]
 [ 0.         -0.25        2.75       -4.25      ]
 [ 0.         -1.25       -1.25        3.75      ]]
[[ 1.         -0.25       -0.25       -0.25      ]
 [ 0.          1.         -0.45454545 -0.09090909]
 [ 0.          0.          1.         -1.62068966]
 [ 0.          0.         -1.81818182  3.63636364]]
[[ 1.         -0.25       -0.25       -0.25      ]
 [ 0.          1.         -0.45454545 -0.09090909]
 [ 0.          0.          1.         -1.62068966]
 [ 0.          0.          0.          1.        ]]
[10.  9. 17.  9.]


Exercise 6.2

In [29]:
import numpy as np
#b)
A = np.array([[2, 1, 4, 1],
              [3, 4, -1, -1],
              [1, -4, 1, 5],
              [2, -2, 1, 3]
], float)

v = np.array([-4, 3, 9, 7], float)
N = len(v)

#Gaussian elimination
for m in range(N):
    pivoting = [abs(A[i, m]) for i in range(m, N)]
    pivot = pivoting.index(max(pivoting)) + m
    A_pivot = A.copy()
    A[m, :] = A_pivot[pivot, :]
    A[pivot, :] = A_pivot[m, :]
    v_pivot = v.copy()
    v[m] = v_pivot[pivot]
    v[pivot] = v_pivot[m]
    div = A[m,m]
    A[m, :] /= div
    v[m] /= div
    
    
    for i in range(m+1, N):
        mult = A[i, m]
        A[i, :] -= mult*A[m, :]
        v[i] -= mult*v[m]
        
#Backsubstitution
x = np.empty(N, float)
for m in range(N-1, -1, -1):
    x[m] = v[m]
    for i in range(m+1, N):
        x[m] -= A[m, i]*x[i] 
    
print(x)

[ 2. -1. -2.  1.]


In [30]:
import numpy as np
#b)
A = np.array([[0, 1, 4, 1],
              [3, 4, -1, -1],
              [1, -4, 1, 5],
              [2, -2, 1, 3]
], float)

v = np.array([-4, 3, 9, 7], float)
N = len(v)

#Gaussian elimination
for m in range(N):
    pivoting = [abs(A[i, m]) for i in range(m, N)]
    pivot = pivoting.index(max(pivoting)) + m
    A_pivot = A.copy()
    A[m, :] = A_pivot[pivot, :]
    A[pivot, :] = A_pivot[m, :]
    v_pivot = v.copy()
    v[m] = v_pivot[pivot]
    v[pivot] = v_pivot[m]
    div = A[m,m]
    A[m, :] /= div
    v[m] /= div
    for i in range(m+1, N):
        mult = A[i, m]
        A[i, :] -= mult*A[m, :]
        v[i] -= mult*v[m]
        
#Backsubstitution
x = np.empty(N, float)
for m in range(N-1, -1, -1):
    x[m] = v[m]
    for i in range(m+1, N):
        x[m] -= A[m, i]*x[i] 
    
print(x)

[ 1.61904762 -0.42857143 -1.23809524  1.38095238]


Exercise 6.3: LU decomposition

In [31]:
import numpy as np
#b)
A = np.array([[2, 1, 4, 1],
              [3, 4, -1, -1],
              [1, -4, 1, 5],
              [2, -2, 1, 3]], float)

v = np.array([-4, 3, 9, 7], float)
N = len(v)
L = np.zeros_like(A)

#Gaussian elimination
for m in range(N):
    pivoting = [abs(A[i, m]) for i in range(m, N)]
    pivot = pivoting.index(max(pivoting)) + m
    A_pivot = A.copy()
    L_pivot = L.copy()
    A[m, :] = A_pivot[pivot, :]
    A[pivot, :] = A_pivot[m, :]
    v_pivot = v.copy()
    v[m] = v_pivot[pivot]
    v[pivot] = v_pivot[m]
    L[m, :] = L_pivot[pivot, :]
    L[pivot, :] = L_pivot[m, :]
    div = A[m,m]
    for i in range(m,N):
        L[i, m] = A[i, m]
    A[m, :] /= div
    #v[m] /= div
    for i in range(m+1, N):
        mult = A[i, m]
        A[i, :] -= mult*A[m, :]
        #v[i] -= mult*v[m]
        
A_ = np.zeros_like(A)
        
for i in range(N):
    for j in range(N):
        for k in range(N):
            A_[i,j] += L[i,k]*A[k,j]
print(L)
#print(A)
#print(A_)
        
#Backsubstitution

y = np.empty(N, float)
for m in range(N):
    y[m] = v[m]
    for i in range(m):
        y[m] -= L[m, i]*y[i]
    y[m] /= L[m,m]
        
#Backsubstitution
x = np.empty(N, float)
for m in range(N-1, -1, -1):
    x[m] = y[m]
    for i in range(m+1, N):
        x[m] -= A[m, i]*x[i] 
    
print("A=", A_)
print(x)

[[ 3.          0.          0.          0.        ]
 [ 1.         -5.33333333  0.          0.        ]
 [ 2.         -1.66666667  4.25        0.        ]
 [ 2.         -4.66666667  0.5        -1.        ]]
A= [[ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2.  1.  4.  1.]
 [ 2. -2.  1.  3.]]
[ 2. -1. -2.  1.]


In [32]:
A = np.array([[2, 1, 4, 1],
              [3, 4, -1, -1],
              [1, -4, 1, 5],
              [2, -2, 1, 3]], float)

v = np.array([-4, 3, 9, 7], float)
np.linalg.solve(A, v)

array([ 2., -1., -2.,  1.])

In [47]:
import numpy as np

A = np.array([[0, 1, 4, 1],
              [3, 4, -1, -1],
              [1, -4, 1, 5],
              [2, -2, 1, 3]
], float)

v = np.array([-4, 3, 9, 7], float)

print("solution using numpy:", np.linalg.solve(A, v))

N = len(v)
L = np.zeros_like(A)
pivot_rec = list(range(N))

#LU decomposition
for m in range(N):
    pivoting = [abs(A[i, m]) for i in range(m, N)]
    pivot = pivoting.index(max(pivoting)) + m
    pivot_rec[m], pivot_rec[pivot] = pivot_rec[pivot], pivot_rec[m]
    A_pivot = A.copy()
    L_pivot = L.copy()
    A[m, :] = A_pivot[pivot, :]
    A[pivot, :] = A_pivot[m, :]
    L[m, :] = L_pivot[pivot, :]
    L[pivot, :] = L_pivot[m, :]
    div = A[m,m]
    for i in range(m,N):
        L[i, m] = A[i, m]
    A[m, :] /= div
    for i in range(m+1, N):
        mult = A[i, m]
        A[i, :] -= mult*A[m, :]
        
        
A_ = np.zeros_like(A)
        
for i in range(N):
    for j in range(N):
        for k in range(N):
            A_[i,j] += L[i,k]*A[k,j]
        
#pivoting
v_copy = v.copy()
for i in range(N):
    v[i]= v_copy[pivot_rec[i]]

#Backsubstitution
y = np.empty(N, float)
for m in range(N):
    y[m] = v[m]
    for i in range(m):
        y[m] -= L[m, i]*y[i]
    y[m] /= L[m,m]
            
#Backsubstitution
x = np.empty(N, float)
for m in range(N-1, -1, -1):
    x[m] = y[m]
    for i in range(m+1, N):
        x[m] -= A[m, i]*x[i] 

print("solution using this program:",x)

solution using numpy: [ 1.61904762 -0.42857143 -1.23809524  1.38095238]
solution using this program: [ 1.61904762 -0.42857143 -1.23809524  1.38095238]
